### ISSUE TITLE
 Error: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries

### ISSUE THREAD

**Issue by suifengshaonian** [easydiffusion/easydiffusion#1010]
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))' thrown while requesting HEAD https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/vocab.json
17:35:03.640 WARNING cuda:0 'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded     _http.py:145
with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by ProxyError('Cannot connect to
proxy.', OSError(0, 'Error')))' thrown while requesting HEAD
https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/vocab.json
17:35:03.643 ERROR cuda:0 Error while loading stable-diffusion model:                                model_manager.py:45
D:\Easy_Diffusion\models\stable-diffusion\sd-v1-4.ckpt
17:35:03.645 ERROR cuda:0 Error: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries   model_manager.py:46
exceeded with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by
ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
17:35:03.647 ERROR cuda:0 Consider removing the model from the model folder.

help！

**Comment by JeLuF** [comment]
It looks like you've used the old installer. Our new installer uses a different way to download these files, which shouldn't be affected by the "Cannot connect to proxy" issue. Please try our new installer: https://github.com/cmdr2/stable-diffusion-ui/releases/download/v2.5.24/Easy-Diffusion-Windows.exe

**Comment by joshshapiro** [comment]
I'm getting a similar HTTPSConnectionPool error when trying to generate using any model. I used the v2.5.24 installer.

`Traceback (most recent call last):
  File "C:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 333, in thread_render
    model_manager.reload_models_if_necessary(renderer.context, task.task_data)
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 119, in reload_models_if_necessary
    action_fn(context, model_type, scan_model=False)  # we've scanned them already
  File
"C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py", line
24, in load_model
    context.models = models.load_model(context, **kwargs)
  File
"C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\_
_init__.py", line 54, in load_model
    model = instantiate_from_config(config.model)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\util.py", line 79, in
instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\models\diffusion\ddpm.py", line
630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\util.py", line 79, in
instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\encoders\modules.py",
line 99, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File
"C:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py",
line 1723, in from_pretrained
    resolved_vocab_files = cached_path(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\utils\hub.py", line 282,
in cached_path
    output_path = get_from_cache(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\utils\hub.py", line 485,
in get_from_cache
    r = requests.head(url, headers=headers, allow_redirects=False, proxies=proxies,
timeout=etag_timeout)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\requests\sessions.py", line 587, in
request
    resp = self.send(prep, **send_kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\requests\sessions.py", line 701, in
send
    r = adapter.send(request, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\requests\adapters.py", line 562, in
send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries
exceeded with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
self signed certificate in certificate chain (_ssl.c:1123)')))`

**Comment by JeLuF** [comment]
> requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries
exceeded with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
self signed certificate in certificate chain (_ssl.c:1123)')))

This error message suggests that something is intercepting your HTTPS traffic, probably a malware scanner, or actual malware.

**Comment by JeLuF** [comment]
closed due to inactivity

**Comment by danfolkes** [comment]
I was able to fix.  ZScaler was my problem.

1. Find where my python pem is: C:\EasyDiffusion\installer_files\env\python.EXE -m certifi
  - C:\EasyDiffusion\installer_files\env\lib\site-packages\certifi\cacert.pem
2. Downloaded my zscaler_root_ca.crt from my org and opened in text editor
3. Added it to my python C:\EasyDiffusion\installer_files\env\lib\site-packages\certifi\cacert.pem
