### ISSUE TITLE
Guest permissions when sharing

### ISSUE THREAD

**Issue by EvilPudding** [easydiffusion/easydiffusion#1336]
I want to share stable diffusion access in my network, or possibly outside it, but I can't find a way of restricting the options guest users would have.

If there isn't a way I missed, it would be nice to be able to block changing settings, merging models, limit the number of parallel tasks, to anyone running outside of localhost.

It would also be nice to be able to pick which models and loras are available to guests, or even allow guests to upload their own models without having access to the machine.

Without these restrictions, it is impossible to use this as a server for other people in a secure way. If that is outside the scope of this project, is there any alternative I should consider?

**Comment by cmdr2** [comment]
Hi @EvilPudding Yes, access controls/permissions aren't yet present in Easy Diffusion. It's been designed primarily for desktop usage (by a single user), or sharing in a trusted network with friends/family (e.g. in a LAN or trusted links).

So a lot of these server-like permissions are lacking, and I don't personally know of alternatives that I can recommend (I'd love to recommend, I just don't know any that have strong security).

If you're interested in adding a few security permission checks, by submitting a pull request (code contribution), I'd love to merge it. Thanks!

Closing this for now, since even though I'd love to make this more robust for server-usage, it's unfortunately not the focus for now. I'm not opposed to merging a PR by someone else, but I won't be able to work on it right now. Thanks!
