### ISSUE TITLE
Easy Diffusion v2.5.22 ->  Make Image-> Error

### ISSUE THREAD

**Issue by Vladimir777777777** [easydiffusion/easydiffusion#1458]
Error: Unexpected Read Error:
Error:undefined
EventInfo: {
    "reader": {}
}

Error: The model for Stable Diffusion has not been loaded yet! If you've tried to load it, please check the logs above this message for errors (while loading the model).

**Comment by JeLuF** [comment]
v2.5.22 is a pretty old version (more than 6 months). A lot of these kinds of issues have been fixed in the meantime. I assume your auto-update process is broken. This can usually be fixed by:

- Stop EasyDiffusion
- Start the `Developer Console.cmd` tool from the EasyDiffusion directory
- In the tool, run these commands, line by line:
```
cd sd-ui-files
git add -A .
git stash 
```
- Restart EasyDiffusion

It should now update to version 3.0

**Comment by cmdr2** [comment]
Please try the latest version released here: https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2

Thanks
