### ISSUE TITLE
System went out of paging space - Pagefile - Windows 11

### ISSUE THREAD

**Issue by Rosiko** [easydiffusion/easydiffusion#1475]
**Is your feature request related to a problem? Please describe.**
Easydiffusion started (and other active processes on Windows 11), results in 60% of RAM memory occupied on 16GB. From the console I see that the Jobs fail with this signal "Reason: Your computer is running out of system RAM!"
Issue #1440 states that "Your system went out of paging space."
Could a priority use of RAM memory be implemented instead of using the pagefile?

Increasing the size of the pagefile they do not encounter problems on EasyDiffusion.
However, this requires a change in the PC configuration by increasing the pagefile space, which is not recommended on HW such as SSD

**Describe alternatives you've considered**
Priority use of RAM memory instead of using the pagefile (if possible).

**Additional context**

**Comment by JeLuF** [comment]
When 60% of memory is allocated, and EasyDiffusion tries to allocate 8GB, its request will fail. The task manager will not show a 100% allocation level, since this 8GB never get allocated.

EasyDiffusion doesn't set its MEMORY_PRIORITY_INFORMATION, so it's using the default value of MEMORY_PRIORITY_NORMAL (5), which is the _highest_ possible value.

**Comment by cmdr2** [comment]
Hi @Rosiko Unfortunately I don't know how to set priority use of RAM, and I'm happy to review/accept pull requests if you'd like to contribute the code for it.

Stable Diffusion is heavy on the system RAM, so there's not much we can do about that right now. We don't make the models, Easy Diffusion is just a software to run the models.

Thanks!
