### ISSUE TITLE
Upscale to Add Details on Integrated Graphics

### ISSUE THREAD

**Issue by fulcrumrebel** [easydiffusion/easydiffusion#1494]
Hi all, I am looking for some resources or recommendations in Easy Diffusion or outside of it.
For background, I have the webUI for Easy Diffusion running on my CPU (Im on integrated graphics for now.)

Ive seen people using A111 to upscale images and actually add detail, not just clean up the resolution. Is there a way to do that in EasyDiffusion without having to run on a GPU? I have a PC with a dedicated graphics card, but I dont want to put my card through it if I dont have to since I use it for work right now.

Looking for recommendations on how to add detail while upscaling in ED or outside sources that will allow me to do it with integrated graphics. Thanks!

**Comment by Releece** [comment]
Why are you hesitant on using your dedicated card? An application can't break your GPU by overloading or sth. The system and your card's bios will first increase cooling if nessecary, and if that's not enough it will just throttle your card (=underclocking) so that it delivers a little less performance but generates less heat. GPU's are made to be able to withstand very high temperatures anyway, I think my GTX1650 super can run in the 70 degrees Celsius and that's considered normal and no problem to stay there for indefinite amount of time (even though I've never seen it go above 50 degrees). 

In any case, just like your CPU, a GPU has an in-built kill-switch that will shutdown the system/GPU if a certain maximum temperature is reached. because of some rare malfunction or sth, so will shutdown long before it could actually get damaged.
Though maybe you know all this already ;P

**Comment by fulcrumrebel** [comment]
> 

I’m not hesitant to use it. I had it before but I also don’t really have the space on my PC for it to add it. It’s also just incredibly convenient for me to generate using my laptop where I can be lazy on the couch versus an office lol. 

I mostly just wanted to know if it was even possible to upscale and add detail with Easy Diffusion because I haven’t actually seen anyone use it that way. Everyone just uses A111 to upscale and add detail

**Comment by Releece** [comment]
Ah you mean your PC Case is small relative to the GPU's size? It's not connected rn? Still sounds like a waste to just let it collect dust, might as well use it for some of your more hardcore rendering sessions :D

Tip for comfort + GPU-render: just install Easy Diffusion on your PC and then you can just access the WEB-UI on your laptop, which is really just the interface and uses little computing. I believe it already hosts itself over LAN-network automatically, but you can even configure it to be reachable over the internet.

I haven't done this detail-upscaling yet, but I'm pretty sure ED can do it. I think I was browsing through the official page with WEB-UI plugins and while reading their descriptions at least one had dedicated functions to execute such tasks.


Edit: Yeah there's multiple on this page:
https://github.com/easydiffusion/easydiffusion/wiki/UI-Plugins

**Comment by fulcrumrebel** [comment]
> Ah you mean your PC Case is small relative to the GPU's size? It's not connected rn? Still sounds like a waste to just let it collect dust, might as well use it for some of your more hardcore rendering sessions :D
> 
> Tip for comfort + GPU-render: just install Easy Diffusion on your PC and then you can just access the WEB-UI on your laptop, which is really just the interface and uses little computing. I believe it already hosts itself over LAN-network automatically, but you can even configure it to be reachable over the internet.
> 
> I haven't done this detail-upscaling yet, but I'm pretty sure ED can do it. I think I was browsing through the official page with WEB-UI plugins and while reading their descriptions at least one had dedicated functions to execute such tasks.
> 
> Edit: Yeah there's multiple on this page: https://github.com/easydiffusion/easydiffusion/wiki/UI-Plugins

100% going to try the plug ins! But I am not sure how to use it so I am researching. Thank you1
