### ISSUE TITLE
Activate "listen_to_network" manually

### ISSUE THREAD

**Issue by numericsgithub** [easydiffusion/easydiffusion#1601]
I cannot reach the localhost:9000 address from my ssh connection on my remote server.
I have no idea where the config.yaml is hidden. There are only two config.yaml.sample files.

How do I tell the tool to run the webserver on 0.0.0.0?

Please add documentation where this seemingly important config file is.

Are the arguments for the start.sh file specified somewhere? If not, please do. If yes, please make it easier to find.

**Comment by cmdr2** [comment]
Hi @numericsgithub Can you please try the documentation for network ports? https://github.com/easydiffusion/easydiffusion/wiki/Config-settings

Usually, you can enable "Listen to Network" using the UI (in the Settings tab), but since you can't access the UI, you can edit `config.yaml` in the Easy Diffusion folder. It's right next to the "start.sh" file.

Please let us know if that didn't work for you. Thanks!
