### ISSUE TITLE
Torch/Torchvision Version in CMD File

### ISSUE THREAD

**Issue by Alexancj919** [easydiffusion/easydiffusion#1688]
Not sure if issue or not, wanted verification.

Currently running Beta v3 through the Start Stable Diffusion UI.cmd shortcut that is made.
Windows 10 Operating System
Nvidia 2070 Super GPU

The cmd runs the check_modules.py
In this listing:
torch has 4 entries ("1.11.0", "1.13.1", "2.0.0", "2.0.1")
and
torchvision has 4 entries ("0.12.0", "0.14.1", "0.15.1", "0.15.2")
all others have one.

Currently my install cmd reads out
Python 3.8.5
torch: 1.13.1+cu116
torchvision: 0.14.1+cu116
Yada Yada

Now, please bear with me because I don't read code very often (never), but aren't the torch and torchvision versions out of date and are basic fallbacks for AMD GPU and Darwin checks.

Should my system be updating to the newest versions by running the cmd?

**Comment by cmdr2** [comment]
Hi, Easy Diffusion doesn't automatically update the torch version, since it's usually a 1.5 GB update. If you want to, you can update the torch version to 2.0.1 (the most-recent version that Easy Diffusion has been tested with).

If you want to update the version of torch, please run `Developer Console.cmd` and then inside the Developer Console, please run this command: `python -m pip install --upgrade torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118`

Please feel free to ask if you have any questions, resolving this for now.
