### ISSUE TITLE
any plans on updating this?

### ISSUE THREAD

**Issue by MikeSavad** [easydiffusion/easydiffusion#1776]
Any plans on updating this? It was going pretty well month after month and then silence. And now all these other versions are coming out in other diffusion things, I can't use a lot of these new models. I'm used to this interface and I don't want to have to try to figure out a new program. 

So i'm wondering when this one will be updated, new samplers, features? Maybe better ram abilities especially with control nets which just get slow as I use them. 

The models with pony?  And COSxl don't work at all for me.

Everyone likes comfy AI but it looks confusing.  

Anyway, will there be any updates in the future?  thanks

**Comment by cmdr2** [comment]
Hi MikeSavad, sorry about the lack of updates.

Easy Diffusion isn't dead, it will continue to work and I'll keep it running. But new features are unlikely for a while. I realize that's disappointing, sorry about that. :/

The current feature-set is supported, so if it's something that's useful, please continue using them. I'll fix any critical bugs that prevent it from working, because ED is still useful to some people, and to newcomers looking to try AI Art.

My real-life work is taking all the hours in the week, and it's unlikely to ease off in the coming few months.

For access to the latest features, I've heard good things about Forge (like askAvoid said), and InvokeAI used to be pretty user-friendly the last time I tried. Thanks!
