### ISSUE TITLE
FLUX TOTALLY CRASHED

### ISSUE THREAD

**Issue by MikeSavad** [easydiffusion/easydiffusion#1872]
Loaded  a gguf, maybe that's why it crashed?  I forgot flux had that. But I tried loading a 9gb model and I think once it loaded it crashed the browser and the screen went black using vivaldi browser. I tried loading  a dv2 flux and couldn't get it to load at all. 

Maybe i'm choosing the wrong flux models? I'm new to flux.

**Comment by cmdr2** [comment]
Hi @MikeSavad You might get better answers and faster help on the Discord server, since a lot more users hang out there and help with queries. https://discord.com/invite/u9yhsFmEkB

I'm closing this ticket for now, because crashes due to memory management in ED 3.5 is a known problem that I'm already tracking elsewhere.

Please try this Flux model - https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/resolve/main/flux1-dev-bnb-nf4-v2.safetensors

**Comment by MikeSavad** [comment]
thanks
