### ISSUE TITLE
Thank you for removing new sampler from new update

### ISSUE THREAD

**Issue by uswin** [easydiffusion/easydiffusion#813]
Hi, I know this might be a bug, i feel like these update about new sampler make this stable diffusion UI so slow and hogging my ram so much (4gb) that it is hard to operate my pc when SD is opened in the browser,

today after i open it, suddenly it goes faster just like before, and when i check the sampler, all those new sampler are gone, so i assume there is still some issue when loading those sampler in the UI.

just make sure new feature like that doesnt hog ram usage. 
thank you  so much for your team hardwork,
 really appreciate it

**Comment by cmdr2** [comment]
Hi @uswin I'm sorry, but we didn't remove any samplers. I think your installation has switch back to the main branch (v2.4) instead of the latest version (v2.5). Can you please tell us which version is displayed at the top of your browser page?

The samplers don't occupy any RAM, they're just different techniques of processing the image. The RAM is used by the model file, and the size of the image you generate. And any other programs running on your PC.

Thanks

**Comment by uswin** [comment]
aah i see, if im not mistaken, my beta is turn on before, but suddenly it is turn off, so im on v2.4 now, which is faster for me than v2.5, for some reason my pc (ram 4gb nvidia gtx970), when loading v2.5 before which contain many sample tend to load so slow, and hog my cpu by a lot, even to start the stable diffusion until "status is ready" will take more than 10 minutes. and even after status is ready, the stable diffusion web gui is taking all of my pc ram, which make me unable to switch to open other program easily such as opening photoshop and others, since my ram usage is around 80% most of the time

for 2.4, with less sample, it only take around 5 minutes for status to be ready, and after that, it doesnot hog my cpu usage, so i can still swiitch back and forth between app and stable diffusion web gui.

can you investigate this behaviour? between v2.4 and 2.5, i do not change any other model/sampler or change anything.

so for now i will stick to v2.4. can you make sure people can revert back to v.2.4 in case im automatically updated to v2.5 ?

thank you so much
